apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexilearn-backend
  namespace: flexilearn-dev
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: ${BACKEND_IMAGE}:${IMAGE_TAG} # <-injecter par jenkins
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: database-url
          
          # Remplace par ta vraie chaîne
        - name: EMAIL_ADDRESS
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: email-address
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: email-password
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: gemini-api-key

        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        
        #volumeMounts:
        #- name: secrets-volume
          #mountPath: "/etc/flexilearn/secrets" # creer automatiquement
          #readOnly: true
     # volumes:
      #- name: secrets-volume
       # secret:
        #secretName: postgres-secrets # Le nom de ton Secret K8s