apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexilearn-frontend
  namespace: flexilearn-dev
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: flexilearn-frontend:prod
        ports:
        - containerPort: 80
