apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexilearn-frontend
  namespace: flexilearn-dev
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: ${FRONTEND_IMAGE}:{IMAGE_TAG}
        ports:
        - containerPort: 80
        
        #volumeMount:
        
        #  - name: config 
        #    mountPath: "/etc/nginx/config.d"
      #volumes: 
      #- name: config
      #  configMap:
      #    name: nginx-settings
