apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: flexilearn-dev
type: Opaque
stringData:
  # Kubernetes va encoder automatiquement ces valeurs en Base64
  postgres-user: "your_user"
  postgres-password: "your_password"
  postgres-db: "db_name"
  database-url: "postgresql://<user>:<password>@postgres-service:5432/flexilearn"
  email-address: "my_email@gmail.com"
  email-password: "app_pass"
  gemini-api-key: ""