apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: flexilearn-dev
type: Opaque
stringData:
  # Kubernetes va encoder automatiquement ces valeurs en Base64
  postgres-user: "admin"
  postgres-password: "admin"
  postgres-db: "flexilearn"
  database-url: "postgresql://admin:admin@postgres-service:5432/flexilearn"
  email-address: "flexilearn575@gmail.com"
  email-password: "ltacwohfnqetirng"
  gemini-api-key: "AIzaSyAeZZUfbpE9f2E5SmQvDWRErffLJTDGUU8"